version: '3'
services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - /etc/ipsec.d/certs:/etc/ipsec.d/certs
      - /etc/ipsec.d/private:/etc/ipsec.d/private
    restart: always